# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('fb_userid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('profile_img_url', models.CharField(max_length=500)),
            ],
        ),
    ]
