# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usershortlistedcourse',
            name='blah',
            field=models.IntegerField(default=0),
        ),
    ]
