# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserShortlistedCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('class_number', models.IntegerField()),
                ('priority', models.IntegerField(default=0)),
            ],
        ),
    ]
