# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 01:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_usershortlistedcourse_blah'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usershortlistedcourse',
            name='blah',
        ),
    ]
